// <auto-generated />
using System;
using Entity1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity1.Migrations
{
    [DbContext(typeof(StudentWebsiteDbContext))]
    partial class StudentWebsiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity1.Clg", b =>
                {
                    b.Property<Guid>("ClgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClgId");

                    b.ToTable("Clgs");

                    b.HasData(
                        new
                        {
                            ClgId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            ClgName = "OxfordCollege"
                        },
                        new
                        {
                            ClgId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            ClgName = "Green Valley Institute"
                        },
                        new
                        {
                            ClgId = new Guid("12e15727-d369-49a9-8b13-bc22e9362179"),
                            ClgName = "Sunrise Engineering College"
                        },
                        new
                        {
                            ClgId = new Guid("8f30bedc-47dd-4286-8950-73d8a68e5d41"),
                            ClgName = "National Arts College"
                        },
                        new
                        {
                            ClgId = new Guid("501c6d33-1bbe-45f1-8fbd-2275913c6218"),
                            ClgName = "Global Science University"
                        });
                });

            modelBuilder.Entity("Entity1.Std", b =>
                {
                    b.Property<Guid>("StdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("StdDprt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StdId");

                    b.ToTable("Stds");

                    b.HasData(
                        new
                        {
                            StdId = new Guid("c03bbe45-9aeb-4d24-99e0-4743016ffce9"),
                            Address = "4 Parkside Point",
                            ClgId = new Guid("56bf46a4-02b8-4693-a0f5-0a95e2218bdc"),
                            DOB = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StdDprt = "CSE",
                            StdName = "Marguerite"
                        },
                        new
                        {
                            StdId = new Guid("c3abddbd-cf50-41d2-b6c4-cc7d5a750928"),
                            Address = "6 Morningstar Circle",
                            ClgId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            DOB = new DateTime(1990, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StdDprt = "ECE",
                            StdName = "Ursa"
                        },
                        new
                        {
                            StdId = new Guid("c6d50a47-f7e6-4482-8be0-4ddfc057fa6e"),
                            Address = "73 Heath Avenue",
                            ClgId = new Guid("14629847-905a-4a0e-9abe-80b61655c5cb"),
                            DOB = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StdDprt = "MECH",
                            StdName = "Franchot"
                        },
                        new
                        {
                            StdId = new Guid("d1a50a47-f7e6-4482-8be0-4ddfc057fa7b"),
                            Address = "12 Lake View Road",
                            ClgId = new Guid("22229847-905a-4a0e-9abe-80b61655c5ab"),
                            DOB = new DateTime(1998, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StdDprt = "CIVIL",
                            StdName = "Anita"
                        },
                        new
                        {
                            StdId = new Guid("e2b60a47-f7e6-4482-8be0-4ddfc057fa8c"),
                            Address = "89 Green Street",
                            ClgId = new Guid("33339847-905a-4a0e-9abe-80b61655c5cd"),
                            DOB = new DateTime(2000, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StdDprt = "IT",
                            StdName = "Ravi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
